apiVersion: v1
kind: Pod
metadata: 
  name: david-pod
  namespace: david-namespace
  labels:
    app: web
spec:
  containers:
    - name: mmumshad-container
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: COLOR
          value: "red"
